/* ============================================================
 * build.js  —  cross-platform static build (Netlify CI + local)
 * ------------------------------------------------------------
 * Copies the static root assets into _deploy/ and runs the
 * bilingual split (split-i18n.js), producing PT (root) + EN (/en/)
 * pages and a fresh sitemap.xml. Pure Node built-ins, so it runs
 * on Netlify's Linux build image AND on Windows.
 *
 *   Netlify:  build command = "node build.js", publish = "_deploy"
 *   Local:    node build.js   (equivalent to deploy.ps1's file step)
 * ============================================================ */
'use strict';
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const root = __dirname;
const out = path.join(root, '_deploy');

// 1) clean output
fs.rmSync(out, { recursive: true, force: true });
fs.mkdirSync(out, { recursive: true });

// 2) static root files (HTML + sitemap are generated by the split, not copied)
for (const f of ['favicon.svg', 'robots.txt', 'og-cover.png', '_redirects']) {
  const p = path.join(root, f);
  if (fs.existsSync(p)) fs.copyFileSync(p, path.join(out, f));
}

// 3) static directories
function copyDir(src, dst) {
  fs.mkdirSync(dst, { recursive: true });
  for (const e of fs.readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, e.name);
    const d = path.join(dst, e.name);
    if (e.isDirectory()) copyDir(s, d);
    else fs.copyFileSync(s, d);
  }
}
for (const dir of ['CV', 'assets']) {
  const p = path.join(root, dir);
  if (fs.existsSync(p)) copyDir(p, path.join(out, dir));
}

// 4) bilingual split (PT root + EN /en/ + sitemap.xml). Uses today's date for lastmod.
const today = new Date().toISOString().slice(0, 10);
execFileSync(process.execPath, [path.join(root, 'split-i18n.js'), root, out, today], { stdio: 'inherit' });

console.log('build.js: _deploy ready (assets + bilingual split)');
